### ISSUE TITLE
Missing the buttons with 0.2.0

### ISSUE THREAD

**Issue by werfpsa** [MichaelOE/home-assistant-MyFisker#10]
I have installed beta version 0.2.0 using HACS.
After restarting HA the buttons are still missing.
My Fisker Ocean has OS version 2.0 and I am based in Europe

**Comment by MichaelOE** [comment]
Hi
Strange...
Have you tried adding them to a dashboard amnually?

![billede](https://github.com/MichaelOE/home-assistant-MyFisker/assets/37800126/fc66ed83-9106-4427-bf2e-f071879fb1d2)

**Comment by werfpsa** [comment]
Hi,
Not possible. After restart My integration only shows 1 device and 63 entities (all sensors). I tried a reload, but no change. HACS shows verstond 0.2.0

**Comment by werfpsa** [comment]
After re-install the buttons are there...
