### ISSUE TITLE
Vehicle range flipping back and forth km /miles ?

### ISSUE THREAD

**Issue by kevinbarmstrong1** [MichaelOE/home-assistant-MyFisker#6]
Hi there and thanks a ton for putting this integration together - it's fantastic !   I did wonder if you or others were seeing something odd around the miles range though ?   Mine has been in the garage for the past 12 hours and fully charged but the sensor randomly changes between 383km and 519km (see chart) - i've actually seen it change on the screen as well, it seems that as its polling the sensor it sometimes get one number and sometimes another.   I thought maybe the API was sending miles vs. km but 519km is 320 miles so that doesn't seem to be the case.

Thoughts ?
Thanks !!
![image](https://github.com/MichaelOE/home-assistant-MyFisker/assets/78314415/f8d9ab10-0156-4a72-8838-b79f953bae98)

**Comment by MichaelOE** [comment]
Hi
Thank you for the kind words 🙏
I am seeing exactly the same, and my first thought was the same - that it flipped between km and miles...
But it is the value that is returned from the API, and for now I think it will be like that.
Maybe when Fisker has the v2.0 released it will change 🤞🙂
