### ISSUE TITLE
OS Version pulling (random) vehicle color?

### ISSUE THREAD

**Issue by 599Rider** [MichaelOE/home-assistant-MyFisker#7]
Just installed, this is great, thanks! Interestingly though, when I put my OS version on my dashboard, the value reported is "STEALTH_GREEN". Doubly funny is that my car is actually Sea Grass. I'm using the US region if that makes a difference.

![image](https://github.com/MichaelOE/home-assistant-MyFisker/assets/46416370/d12be720-8337-4faa-99c1-1b89cf5e27b4)

**Comment by MichaelOE** [comment]
Hmm, strange. Never seen that before.
I will have to look into it I can make some debug-info for you.
Or maybe the API respond different between Europe and the US 🤔.
I am on business trip the next couple of days, but will see if I can find a moment to look into this.

**Comment by MichaelOE** [comment]
I have now the same issue myself - might be caused by Fisker changing the API... will take a look soon

**Comment by MichaelOE** [comment]
Fixed in v0.0.9
